# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 58bd2123fc00b45bdf7d162531f9827224c3f3c9d5d2414cec897e9022d2b7da60c5c12b1be70d0d195580719ffc30b9e5b438e25c8a6f0b11f37ea220bdd8ea

test:
  secret_key_base: f5e8202cdadf7ecb04c6978246ba06e3f168f0db47978f9d2596446e15bfb9c6fd5f8dec3ca910c66b61ac9393fa08976727a0c9ff6d78e6d0bc06b1064c321d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
